import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/Navbar";
import { AuthProvider } from "@/store/AuthContext";
export const metadata: Metadata = {
  title: "Probation Tracking System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@500;700&display=swap" rel="stylesheet" />
      </head>
      <body>
        <AuthProvider>
         <Navbar/>
        <main className="pt-16">{children}</main>
       </AuthProvider>
      </body>
    </html>
  );
}
